---
version: '3.7'

networks:
  default:
    external:
      name: ks2020_network

services:

  prometheus:
    hostname: prometheus
    container_name: ks2020_prometheus
    image: prom/prometheus
    privileged: true
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - '9090:9090'

  grafana:
    hostname: grafan
    container_name: ks2020_grafana
    image: grafana/grafana
    ports:
      - '3000:3000'
    environment:
      GF_SECURITY_ADMIN_PASSWORD: grafana
    volumes:
      - ./grafana/grafana.db:/var/lib/grafana
      - ./grafana/prometheus.yml:/etc/grafana/provisioning/datasources/prometheus.yml
      - ./grafana/dashboards.yml:/etc/grafana/provisioning/dashboards/dashboards.yml
      - ./grafana/dashboards:/var/lib/grafana/dashboards
