kafka:
  security-protocol: PLAINTEXT
  bootstrap-servers:
    - broker-1:9092
    - broker-2:9092
    - broker-3:9092
    - broker-4:9092
  schema-registry: http://schema-registry:8081

application:
  origins:
    - http://35.239.173.178:8080